version: '3'
services:
  eventstore:
    image: "eventstore/eventstore"
    ports:
      - "2133:2133"
      - "1113:1113"
    environment:
      EVENTSTORE_RUN_PROJECTIONS: "All"
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
    networks:
      - app_net
